In [1]:
import numpy as np
from keras_facenet import FaceNet
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
import os

2024-11-11 16:19:52.365747: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-11 16:19:52.552714: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-11 16:19:52.714579: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1731363592.860310   61022 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1731363592.898906   61022 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-11 16:19:53.240735: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [2]:
embedder = FaceNet()

W0000 00:00:1731363603.903120   61022 gpu_device.cc:2344] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [79]:
def directory_face_detection(root_directory):
    face_data = {}
    for root, _, files in os.walk(root_directory):
        for file in files:
            image_path = os.path.join(root, file)
            print(image_path)
            detection = embedder.extract(image_path)
            label = os.path.basename(root)
            # Add to our data structure
            if label not in face_data:
                face_data[label] = []
            face_data[label].append(detection)  
    return face_data

In [11]:
student_image_face_data = directory_face_detection("../../data/images")

../../data/images/2009017/4.jpg


2024-11-04 03:45:33.970809: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 171643392 exceeds 10% of free system memory.
2024-11-04 03:45:34.219199: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 171643392 exceeds 10% of free system memory.
2024-11-04 03:45:34.459334: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 171643392 exceeds 10% of free system memory.
2024-11-04 03:45:34.688149: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 171643392 exceeds 10% of free system memory.
2024-11-04 03:45:34.915327: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 171643392 exceeds 10% of free system memory.


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
../../data/images/2009017/2.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
../../data/images/2009017/3.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
../../data/images/2009017/1.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
../../data/images/2109041/4.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
../../data/images/2109041/2.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
../../data/images/2109041/3.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
../../data/images/2109041/1.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
../../data/images/2109155/4.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
../../data/images/2109155/2.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
../../data/images/2109155/3.jpg
../../data/images/2109155/1.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
../../data/images/2109136/2.jpeg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
../../data/images/2109136/3.jpeg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
../../data/images/2109136/1.jpeg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
../../data/images/2

In [13]:
import joblib

In [13]:
joblib.dump(student_image_face_data, "student_image_face_data.pkl")

['student_image_face_data.pkl']

In [16]:
len(student_image_face_data.keys())

16

In [17]:
for key in student_image_face_data.keys():
    print(key)

2009017
2109041
2109155
2109136
1909123
2109111
2009151
2109107
2109084
2109165
2109146
2109120
2109062
2109108
2109020
2109022


In [31]:
embeddings = []
labels = []
for key in student_image_face_data.keys():
    for image in student_image_face_data[key]:
        if len(image) != 0:
            embeddings.append(image[0]["embedding"])
            labels.append(key)

In [35]:
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

In [36]:
encoded_labels

array([ 1,  1,  1,  1,  5,  5,  5,  5, 14, 14, 14, 12, 12, 12, 12,  0,  0,
        0,  0, 10, 10, 10,  2,  2,  2,  8,  8,  8,  8,  7,  7,  7,  7, 15,
       15, 15, 15, 13, 13, 13, 13, 11, 11, 11, 11,  6,  6,  6,  6,  9,  9,
        9,  9,  3,  3,  3,  3,  4,  4,  4,  4])

In [37]:
joblib.dump(label_encoder, "label_encoder.pkl")

['label_encoder.pkl']

In [ ]:
classifier = SVC(kernel="linear", probability=True)
classifier.fit(embeddings, encoded_labels)

SVC(kernel='linear', probability=True)

In [39]:
joblib.dump(classifier, "face_recog_model.pkl")

['face_recog_model.pkl']

In [3]:
detection = embedder.extract("test_pic1.jpg")

1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step


In [4]:
detection[0]["embedding"]

array([ 0.0079404 , -0.02182912, -0.02811151,  0.00212288,  0.00417509,
        0.05167665,  0.0316264 ,  0.09622376, -0.00099078,  0.08782085,
        0.01075258,  0.04771016,  0.04699546,  0.02939938, -0.06136156,
       -0.01333329, -0.02747018,  0.07876656, -0.05437666, -0.02807498,
        0.02779663,  0.01632985,  0.02170806, -0.01351163,  0.01361792,
       -0.01025501, -0.08153321,  0.01698739, -0.0221024 , -0.06552134,
        0.05779358, -0.0238307 ,  0.01219746, -0.05038081,  0.04981783,
        0.01169136,  0.01657089, -0.02710698, -0.00392555, -0.04957247,
       -0.01017906,  0.01908257,  0.00616247,  0.02255091,  0.02371252,
        0.05350382, -0.03887055, -0.06634676,  0.0334478 , -0.05124959,
        0.00846398, -0.08229119,  0.03018117,  0.02375755, -0.04748849,
        0.03420946, -0.03086182, -0.0345887 , -0.09360491, -0.06074635,
       -0.01525407,  0.04735817, -0.12371948,  0.03662063, -0.09869345,
       -0.06270645, -0.0002213 ,  0.0237909 ,  0.11642759,  0.02

In [6]:
import json

In [11]:
json.dumps(detection[0]["embedding"].tolist())

'[-0.01705324463546276, 0.010529197752475739, 0.008312731981277466, -0.03725671395659447, 0.04719559848308563, 0.052207231521606445, 0.05617243051528931, 0.0526840016245842, -0.003696434199810028, 0.07273057103157043, -0.02858760952949524, 0.06031206250190735, 0.038254864513874054, 0.027699491009116173, -0.048611272126436234, -0.03402500972151756, -0.04218905419111252, 0.04657100513577461, -0.02913084253668785, 0.008998938836157322, 0.04660690948367119, 0.019771410152316093, 0.010810409672558308, -0.040521662682294846, 0.035036906599998474, 0.004997090436518192, -0.027814751490950584, 0.02763528749346733, 0.0009903096361085773, -0.08638874441385269, 0.07280128449201584, -0.04188041388988495, -0.013125560246407986, -0.033978093415498734, 0.09036742895841599, 0.03327126428484917, 0.024228401482105255, -0.025924216955900192, -0.012555000372231007, -0.011802149005234241, 0.012471973896026611, 0.061522506177425385, 0.04949786141514778, -0.00350570073351264, -0.03427876904606819, 0.010181375

In [69]:
test_prediction = classifier.predict([detection[0]["embedding"]])

In [70]:
classifier.predict_proba([detection[0]["embedding"]])

array([[0.03042112, 0.08813599, 0.04661431, 0.05633212, 0.07988399,
        0.05247591, 0.03425937, 0.0576096 , 0.04669605, 0.03647288,
        0.04965257, 0.042636  , 0.04252026, 0.1779476 , 0.0773697 ,
        0.08097255]])

In [71]:
label_encoder.inverse_transform(test_prediction)

array(['2109146'], dtype='<U7')

In [75]:
import sklearn
print(sklearn.__version__)

1.5.2


In [14]:
student_image_face_data = joblib.load("student_image_face_data.pkl")

In [15]:
student_image_face_data

{'2009017': [[{'box': [511, 774, 1226, 1660],
    'confidence': np.float64(0.9999971389770508),
    'keypoints': {'nose': [np.int64(1137), np.int64(1924)],
     'mouth_right': [np.int64(1357), np.int64(2135)],
     'right_eye': [np.int64(1438), np.int64(1519)],
     'left_eye': [np.int64(851), np.int64(1520)],
     'mouth_left': [np.int64(905), np.int64(2136)]},
    'embedding': array([-0.02968525,  0.00977144, -0.02321383,  0.03196165,  0.00196251,
            0.06739984,  0.00812014, -0.04121978,  0.03102306,  0.04180733,
            0.02457494,  0.02648094, -0.00053967,  0.06119168, -0.03537888,
           -0.01498183, -0.0189848 ,  0.07061891,  0.02505046,  0.00529415,
           -0.01948906, -0.01577867,  0.04843838, -0.05389961, -0.0241137 ,
           -0.00803436, -0.04028319, -0.04882921, -0.02214373, -0.02105888,
            0.04618301,  0.06410739,  0.0087924 ,  0.01829353,  0.02129881,
           -0.02448899,  0.03530902, -0.05694875, -0.03344022,  0.02027162,
           -0.

In [6]:
import joblib

In [7]:
joblib.dump(detection[0]["embedding"], "current_embedding.pkl")

['current_embedding.pkl']